rm(list=ls())
library(GaussSuppression)
library(dplyr)
library(rtauargus)
library(SSBtools)
library(tidyverse)
library(curl)
library(readxl)

T2_SP_EI <- readRDS("X:/HAB-Traitement-Confidentialite/TESTS/Gauss/T2_SP_EI.rds")
corr_APE <- readRDS("X:/HAB-Traitement-Confidentialite/TESTS/Gauss/corr_APE_ag.rds")
str(T2_SP_EI)
T2_SP_EI %>% count(is_secret_prim)
length(unique(T2_SP_EI$APE))*length(unique(T2_SP_EI$TREFF_ET))*length(unique(T2_SP_EI$DEP_ET))
str(corr_APE)